name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your GitHub repo
        uses: actions/checkout@v2

      - name: Deploy to Hugging Face
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"

          git clone https://Pranavj24:${HF_TOKEN}@huggingface.co/spaces/Pranavj24/news-sentiment-analyzer hf-space

          rsync -av --exclude='hf-space' ./ hf-space/

          cd hf-space
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes"
          git push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
