name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # or 'master' if your default branch is that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your GitHub repo
        uses: actions/checkout@v2

      - name: Clone Hugging Face Space
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"

          # Clone the HF Space
          git clone https://Pranavj24:${HF_TOKEN}@huggingface.co/spaces/Pranavj24/news-sentiment-analyzer hf-space

          # Copy contents EXCLUDING the hf-space folder
          rsync -av --exclude='hf-space' ./ hf-space/

          # Commit and push
          cd hf-space
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"
          git push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
